// Original Superdub articles, written for the Success Kit.
export type Block =
  | { t: 'h'; text: string }
  | { t: 'p'; text: string }
  | { t: 'li'; text: string }
  | { t: 'quote'; text: string };

export interface Article {
  id: string;
  title: string;
  author: string;
  readMins: number;
  tag: string;
  accent: string;   // cover accent
  dek: string;      // one-line standfirst
  body: Block[];
}

export const ARTICLES: Article[] = [
  {
    id: 'choose-your-prompts',
    title: 'Only the Check-ins You Actually Want',
    author: 'Ali Shah',
    readMins: 2,
    tag: 'Settings',
    accent: '#19C5B0',
    dek: 'Turn the daily prompts on or off one by one, skip the weigh-in when you are not on a plan, and answer mood and energy from a blank slider.',
    body: [
      { t: 'p', text: 'Superdub asks a few small things through the day: your weight in the morning, how you slept, your energy, your mood. Useful when you want them, noise when you do not. So now you choose which ones you get.' },
      { t: 'h', text: 'Pick your prompts' },
      { t: 'p', text: 'Open the menu and look for Daily prompts. There are four switches: Weigh-in, Sleep, Energy and Mood. Flip off the ones you would rather skip and they stop appearing. Turn a field back on and it comes straight back. If a prompt has nothing left switched on, it quietly stops opening at all.' },
      { t: 'h', text: 'No plan, no weigh-in' },
      { t: 'p', text: 'The morning weigh-in now follows your plan. If you have an active weight plan it stays on, because the daily reading is what makes the plan work. If you are not running one, it starts off, so you are not asked to step on the scales every morning for no reason. You can always switch it back on from the same menu.' },
      { t: 'quote', text: 'The best prompt is one you actually wanted.' },
      { t: 'h', text: 'A blank slider for mood and energy' },
      { t: 'p', text: 'Mood and energy used to open with the slider already sitting in the middle, which quietly nudged your answer. Now the slider starts blank, with no point at all. You tap and slide to lock in where you really are, and nothing is chosen for you until you do. Open the menu, set your prompts the way you like them, and Superdub will only ask for what you asked it to. 🎚️' },
    ],
  },
  {
    id: 'habit-runs-on-a-day',
    title: 'Give a Habit the Day It Runs On',
    author: 'Ali Shah',
    readMins: 2,
    tag: 'Habits',
    accent: '#2E8BFF',
    dek: 'Weekly, monthly and yearly habits can now pin the exact day they happen, so the tick lands right and the nudge comes at the right time.',
    body: [
      { t: 'p', text: 'A weekly habit is rarely "some time this week." Laundry is Sunday. The budget review is the first of the month. The dentist is one date a year. Until now a non-daily habit just wanted one tick somewhere in its period, which is fine, but it could not say when. Now it can.' },
      { t: 'h', text: 'Pick the day' },
      { t: 'p', text: 'Open any weekly, monthly or yearly habit. Under the calendar you will find a new line: the day it runs on. A weekly habit picks a weekday, a monthly one picks a date, and a yearly one picks a month and a day. Prefer the old anytime rhythm? Leave it on Any day and nothing changes.' },
      { t: 'quote', text: 'A habit with a day is a habit with a plan.' },
      { t: 'h', text: 'It follows through' },
      { t: 'p', text: 'Once a habit has a day, the rest lines up behind it. The circle by the title and the calendar aim at that day, so a quick tick marks the right one. The Today tab brings the habit up as its day approaches, and flags it if the day passes and it is still not done. And if you set a reminder, the push arrives only on its day, not every morning of the week.' },
      { t: 'h', text: 'Set one now' },
      { t: 'p', text: 'Open a weekly habit, choose its weekday, and watch it appear in Today when the day is near. One small setting, and your longer-rhythm habits finally keep proper time. 📌' },
    ],
  },
  {
    id: 'not-applicable-days',
    title: 'Some Days It Just Does Not Apply',
    author: 'Ali Shah',
    readMins: 3,
    tag: 'Habits',
    accent: '#FFD233',
    dek: 'A new Not Applicable mark lets a habit sit out a day without hurting your streak, unlogged days now show a yellow question mark, and Progress gets a Today list.',
    body: [
      { t: 'p', text: 'Real life does not run on a perfect grid. You travel, a gym closes, a rest day is the healthy choice. Marking those days as missed felt like a lie, and leaving them blank quietly ate your streak. So habits now have a fourth state that simply means this one did not count today.' },
      { t: 'h', text: 'Done, missed, and now N/A' },
      { t: 'p', text: 'Tap a weekday circle to mark it done, double tap to mark it missed, and press and hold to set Not Applicable. It shows as a calm grey dash. The difference that matters: an N/A day is neutral. It never counts as a miss and it never breaks your streak, it just steps aside. The big button and the calendar walk the full cycle for you: done, missed, N/A, then blank.' },
      { t: 'quote', text: 'A day that did not apply is not a day you failed.' },
      { t: 'h', text: 'The yellow question mark' },
      { t: 'p', text: 'A past day you never got round to logging used to look like an empty ring, easy to mistake for nothing. Now it shows a soft yellow question mark, so a day you simply did not report reads differently from a day you actively skipped or missed. It is a gentle nudge, not a red mark.' },
      { t: 'h', text: 'A Today worth opening' },
      { t: 'p', text: 'Progress has a new Today tab. It gathers your to-dos due between now and the end of the week, and it flags any weekly or monthly habit whose window is closing within three days and is still not done. It is the short list of what actually needs you soon, in one place.' },
      { t: 'h', text: 'Weight Plan, clearly labelled' },
      { t: 'p', text: 'Your weight gauge, weekly trend and steps now live under their own Weight Plan tab. Set a goal and it is all there. Have not set one yet? The tab shows a simple prompt to start a plan. While we were here we also let the Habits section list the habits for the cadence you pick, gave the calendar a smooth open and close, and calmed the over-target calorie ring to a steady yellow instead of a flash of red. Open Progress, swipe to Today, and press and hold a habit day the next time life gets in the way. 🟡' },
    ],
  },
  {
    id: 'plan-back-on-today',
    title: 'Your Plan, Back Where You Look Every Day',
    author: 'Ali Shah',
    readMins: 2,
    tag: 'Progress',
    accent: '#2E8BFF',
    dek: 'The weight-journey gauge, your weekly trend and your step count return to the Today tab, so the whole picture is one glance away.',
    body: [
      { t: 'p', text: 'When the app moved to its six clean tabs, the old Plan screen stepped back to make room. The intent was always to fold its best parts into Progress, and that never quite happened, so the Today tab ended up a little bare. This puts it right.' },
      { t: 'h', text: 'The gauge you missed' },
      { t: 'p', text: 'Open Progress and tap Today. The semi-circle is back: your current weight sits big in the middle, the arc sweeps from where you started round to your goal, and a small bar underneath shows how much of your time you have used. One look tells you if you are ahead of the clock or behind it.' },
      { t: 'quote', text: 'A goal you can see is a goal you keep.' },
      { t: 'h', text: 'The week, and your steps' },
      { t: 'p', text: 'Under the gauge sits Weight This Week: your logged weigh-ins, a smoothed line through the noise, your 28-day direction and the golden safe-zone corridor around the ideal path. Below that, your step goal for today and how yesterday landed. The trend, the target and the movement, together.' },
      { t: 'h', text: 'Nothing lost' },
      { t: 'p', text: 'The full Plan page, with your calorie target, the adaptive engine and Smart Adjust, is still there any time you want the detail: open the cog menu and tap it. And the grey Quit panel on Habits now sits just to the left of Daily, one swipe away, while the page still opens on Daily each day. Open Today and take it all in. 🎯' },
    ],
  },
  {
    id: 'make-it-yours',
    title: 'Make It Yours: Star, Reorder, and Gender Dub',
    author: 'Ali Shah',
    readMins: 2,
    tag: 'Habits',
    accent: '#FFB928',
    dek: 'Three small touches that turn a list of habits into your list, arranged your way, coached by a companion who is who you say they are.',
    body: [
      { t: 'p', text: 'The best habit tracker is the one that feels like yours. Not a generic list handed to you, but your things, in your order, watched over by a companion you chose. So this update is three small, human touches rather than one big feature.' },
      { t: 'h', text: 'Star what matters' },
      { t: 'p', text: 'Some habits carry more weight than others. Tap the star on any habit card and it becomes a favourite. Your starred habits then surface on the Progress page, under both Today and Yesterday, so the ones you care most about are always a glance away, whether you are ahead on them or not.' },
      { t: 'h', text: 'Drag them into order' },
      { t: 'p', text: 'Your list should read the way your day runs. Grab the handle on the left of any habit card and drag it up or down. Let go and the new order sticks. Put the morning ones first, the wind-down ones last, whatever makes sense to you.' },
      { t: 'quote', text: 'Small choices about how a thing looks are how it starts to feel like yours.' },
      { t: 'h', text: 'Dub, as you see them' },
      { t: 'p', text: 'Dub has always been a bit of a he by default, but that was never really a decision, just a habit of ours. Now it is yours to make. Open Profile, find the Companion section next to where you pick the dog or the cat, and choose he, she or they. Dub\'s coaching updates to match. Star one habit, drag it to the top, set your pronouns, and it is already a little more your Superdub. ⭐' },
    ],
  },
  {
    id: 'journal-with-a-mood',
    title: 'A Journal, and Why It Has a Mood',
    author: 'Ali Shah',
    readMins: 2,
    tag: 'Lists',
    accent: '#19C5B0',
    dek: 'A quiet place to write a line about your day, and a small mood tag that quietly teaches Dub what actually lifts you.',
    body: [
      { t: 'p', text: 'Numbers tell you what happened. They rarely tell you why. You can see a low-step day on the chart, but not the argument, the bad night, or the small win that came with it. So Lists now has a Journal: a plain, private place to write a line or a paragraph about your day, whenever you feel like it.' },
      { t: 'h', text: 'Where to find it' },
      { t: 'p', text: 'Open Lists and you will see a new tab next to Goals, called Journal. Tap New entry, write whatever is on your mind, and save. Your entries stack newest first, each stamped with the time you wrote it.' },
      { t: 'h', text: 'The mood is the clever bit' },
      { t: 'p', text: 'Under the text you can tag how you felt, from rough to great. It is optional and it takes one tap, but it is doing quiet work. That mood is a signal, and Dub reads it. Alongside your evening check-ins, your journal moods feed the patterns he surfaces: whether the days you keep a habit are also your better days, whether more steps really do lift you.' },
      { t: 'quote', text: 'Write the sentence you would tell a friend. The mood tag turns it into data without killing the feeling.' },
      { t: 'h', text: 'Yours, quietly' },
      { t: 'p', text: 'Nothing here is shared and nothing is judged. Write one honest line, tag the mood, and let Dub connect it to the rest over time. Open Lists, tap Journal, and start with today. 📓' },
    ],
  },
  {
    id: 'habits-to-quit',
    title: 'Habits to Quit: A Clock That Counts Up',
    author: 'Ali Shah',
    readMins: 2,
    tag: 'Habits',
    accent: '#8A8F98',
    dek: 'Some habits you build by ticking them off. Others you beat by simply not doing them, one clean hour at a time.',
    body: [
      { t: 'p', text: 'Every habit in Superdub so far has been about doing something: walk, read, drink water, tick it off. But some of the most important habits are the opposite. Stopping smoking. Cutting the late-night scroll. The thing you know you are better off without. You do not tick those off. You just go without, and the longer you go the bigger the win.' },
      { t: 'h', text: 'Where to find it' },
      { t: 'p', text: 'Open the Habits page and swipe your cards to the left, past Daily, Weekly, Monthly and Yearly. At the end sits a new panel in calm grey: Quit. Add the thing you are giving up, and tell it when you actually stopped, right down to the hour.' },
      { t: 'quote', text: 'You do not have to be perfect. You just have to keep the clock running.' },
      { t: 'h', text: 'A timer, not a checkbox' },
      { t: 'p', text: 'From that moment a clock counts up: days, hours, minutes, seconds, live. A bar fills alongside it and reaches full at your first 30 clean days. There is nothing to remember and nothing to tap each day. Time passing is the whole point, and the clock does that for you.' },
      { t: 'h', text: 'If you slip' },
      { t: 'p', text: 'You might slip. Most people do, and it is not the end of anything. Tap Rewind and the clock simply restarts from now. No guilt trip, no lecture, no wiped record. Just a clean run beginning again, which is exactly how quitting actually works. Swipe over, set your start, and watch the time add up. ⏱' },
    ],
  },
  {
    id: 'dub-gets-a-tab',
    title: 'Dub Gets His Own Tab, and a Sharper Eye',
    author: 'Ali Shah',
    readMins: 2,
    tag: 'Dub',
    accent: '#2E8BFF',
    dek: 'Your coach steps out of the shadows into his own spot on the bar, and starts reading your data for the patterns you cannot see day to day.',
    body: [
      { t: 'p', text: 'Dub has always been in Superdub, popping up after a weigh-in with a kind word and a read on your trend. The trouble was you could only reach him at that one moment. So we gave him a home: his own tab, right in the middle of the bottom bar, there whenever you want him.' },
      { t: 'h', text: 'Where Profile went' },
      { t: 'p', text: 'To make room, Profile moved into the cog menu at the top right. That is where all your settings, your plan and your customization already lived, so it is one tidy place now instead of two. Tap the cog, tap Profile, same as ever.' },
      { t: 'h', text: 'A check-in on demand' },
      { t: 'p', text: 'Open Dub and the first thing you get is a straight read on where you are: your weight trend, your habits, what is going well and what is slipping. Want the full report he gives after a weigh-in? Tap "Check in with Dub" any time you like.' },
      { t: 'quote', text: 'The patterns that trip you up are rarely the ones you notice in the moment.' },
      { t: 'h', text: 'The sharper eye' },
      { t: 'p', text: 'Here is the real upgrade. Dub now reads back through your own history and tells you what it is quietly saying. Which weekday a habit slips most, so you can plan for it. Whether the days you keep a habit are also your higher-step days or your better-mood days. Even whether the weeks you hold a habit are the weeks your weight actually comes down.' },
      { t: 'p', text: 'It is all worked out on your device, from your numbers, no cloud and no guessing. Give it about ten days of logging to warm up, then open Dub and see what he has found. 🐾' },
    ],
  },
  {
    id: 'the-global-habit',
    title: 'The Global Habit: One Thing, All of Us',
    author: 'Ali Shah',
    readMins: 2,
    tag: 'Superdub',
    accent: '#FFB928',
    dek: 'A slowly turning planet by your level ring opens one shared habit that the whole community levels up together.',
    body: [
      { t: 'p', text: 'Every habit in Superdub so far has been yours alone. This one is different. There is now a small planet, slowly turning, sitting just to the top left of your level ring. Tap it and you meet The Global habit: one thing, the same for everyone, for the whole month.' },
      { t: 'h', text: 'This month: do a good deed' },
      { t: 'p', text: 'That is the whole ask. Hold a door, text a friend back, pick up the litter nobody else did. Then open the planet and log it. Once a day, no streak pressure, no guilt if you miss one.' },
      { t: 'quote', text: 'Small and shared beats big and alone.' },
      { t: 'h', text: 'You level it up, we climb together' },
      { t: 'p', text: 'Each deed levels the habit up for you personally, exactly like your other habits, and it pays more XP the longer you keep at it. But here is the twist: all of that XP flows into one shared total that every Superdubber is filling at the same time. You are never climbing on your own.' },
      { t: 'h', text: 'The reward is white' },
      { t: 'p', text: 'When we reach 10,000 XP together, a new colour opens up for Dub: pure, calm white. It only goes to people who actually showed up, so you need at least 100 XP of your own in the pot. When it unlocks it simply appears in your Level page, ready to equip whenever the mood takes you. Tap the planet, do one good thing, and add your bit to the climb. 🌍' },
    ],
  },
  {
    id: 'live-target-matrix',
    title: 'Your Day, as a Live Target Matrix',
    author: 'Ali Shah',
    readMins: 2,
    tag: 'Progress',
    accent: '#FFD233',
    dek: 'The Today tab stopped reporting the past and started coaching the present: four gauges of live pace and buffer.',
    body: [
      { t: 'p', text: 'The old Today view told you about yesterday. Useful once, but by the time you are looking at it, the day is already moving. So we rebuilt it around a simple question: right now, are you ahead or behind?' },
      { t: 'h', text: 'Four gauges, all live' },
      { t: 'p', text: 'Intake is a runway, not a tally: it shows how many calories you have left against target, and if you cross the line it flashes a critical buffer so there is no pretending. Activity does not just count steps, it counts them against where you should be by this hour, then tells you how far ahead or behind pace you are.' },
      { t: 'p', text: 'Vitals pairs last night\'s sleep with a prediction of your afternoon energy, because a short night usually shows up around 3pm whether you planned for it or not. Focus picks the single habit still open today and puts it one tap away, so the thing most at risk of slipping is the thing in front of you.' },
      { t: 'quote', text: 'A number about yesterday is history. A buffer about right now is a decision.' },
      { t: 'h', text: 'Frozen in place, on purpose' },
      { t: 'p', text: 'The matrix is locked to the exact size of your trend charts, and the chart chips now sit right underneath it. Tap between Today, Weight, Steps and the rest and nothing jumps: the frame stays put, only the content changes. Less visual noise, less fatigue, more logging.' },
      { t: 'p', text: 'Open Progress, glance at the four gauges, and do the one small thing they are pointing at. That is the whole loop. 🎯' },
    ],
  },
  {
    id: 'reminders-that-fit',
    title: 'Reminders That Fit Your Day',
    author: 'Ali Shah',
    readMins: 2,
    tag: 'Superdub',
    accent: '#FFB928',
    dek: 'Three gentle nudges timed to your real routine, and a row of tokens that light up as you close each loop.',
    body: [
      { t: 'p', text: 'A reminder is only useful if it lands at the right moment. One 8am buzz cannot cover a whole day, so notifications now come in three parts, each set to a time that suits you, and each smart enough to stay quiet once you have already done the thing.' },
      { t: 'h', text: 'Pick your three times' },
      { t: 'p', text: 'Open the menu, turn Notifications on, and you will see three time pickers. Morning is your weigh-in nudge. Nutrition is an evening check to log how eating landed against your target. Workout is optional (leave it Off if you like): set it to roughly thirty minutes after you usually finish training, and it will ask the one question that matters.' },
      { t: 'quote', text: 'Did you close your exercise loop today? One tap, and the day is honest.' },
      { t: 'h', text: 'Tap it, and you are already there' },
      { t: 'p', text: 'Every reminder deep-links to the exact place that answers it. The weigh-in opens your morning check-in, the workout nudge opens your daily ritual, and the nutrition one drops you into Food Log. No hunting through the app.' },
      { t: 'h', text: 'The Core Habits matrix' },
      { t: 'p', text: 'On The Ascension, just under your level ring, four tokens track the loops that feed everything else: Weight, Sleep and Energy, Steps, Calories. Each one is dim until you close it, then it lights gold. A quick glance tells you what is left before the day is fully logged.' },
      { t: 'p', text: 'Set your three times once, then just answer the taps as they come. Log, see the trend, get your read, do one small thing. 🔔' },
    ],
  },
  {
    id: 'sleep-candles',
    title: 'Your Sleep, as Candlesticks',
    author: 'Ali Shah',
    readMins: 2,
    tag: 'Sleep',
    accent: '#8B5CF6',
    dek: 'Every night is a candle: the body is the hours you slept, the colour is how you woke up feeling.',
    body: [
      { t: 'p', text: 'Sleep used to show up as a simple line of hours. Useful, but it hid the two things that actually matter: when you went to bed, and how that night left you feeling the next morning. So we rebuilt it as a candlestick chart.' },
      { t: 'h', text: 'How to read a candle' },
      { t: 'p', text: 'Each night is one candle. The body runs from the time you went to bed down to the time you woke up, so a longer candle simply means more sleep. The vertical axis is the clock, evening at the top and morning at the bottom, which is why a night that crosses midnight still reads as one clean bar.' },
      { t: 'h', text: 'The colour is the point' },
      { t: 'p', text: 'Here is the part worth staring at: each candle is coloured by the mood you logged the next morning. Green is a good morning, red is a rough one, amber sits in between. Line up a week of candles and the pattern jumps out, the late nights that turn the next day red, or the run of early nights that keeps you green.' },
      { t: 'quote', text: 'You cannot fix what you cannot see. Now you can see the night behind the mood.' },
      { t: 'h', text: 'Do this tonight' },
      { t: 'p', text: 'Open your daily check-in and log the time you went to bed and the time you woke. Do it for a few nights, then swipe to the Sleep card on Progress and read the colours. One honest week is usually enough to spot the trade you have been making. 😴' },
    ],
  },
  {
    id: 'meet-dub',
    title: 'Meet Dub, Your Coach',
    author: 'Ali Shah',
    readMins: 2,
    tag: 'Superdub',
    accent: '#2FD27E',
    dek: 'The little robo-pup who keeps you honest, cheers your wins, and asks for a walk.',
    body: [
      { t: 'p', text: 'Say hello to Dub, the small robotic Yorkie living inside Superdub. Dub isn\'t a gimmick; he\'s how your data talks back to you in plain, kind English.' },
      { t: 'h', text: 'What Dub does' },
      { t: 'p', text: 'Every time you weigh in, Dub reads your numbers, your weight trend, your habit streaks, what you\'ve been skipping, and gives you one short, honest read. A win to protect, something slipping, and a tiny next step. No shame, no spreadsheets. Just a nudge from someone (something?) on your side.' },
      { t: 'p', text: 'You\'ll also find Dub sitting by your level ring on the home screen, and at the top of your Progress page rating how things are trending. Tap him any time you want a read, you don\'t have to wait for a weigh-in.' },
      { t: 'h', text: 'Dub likes walks' },
      { t: 'p', text: 'Here\'s the thing about Dub: when you go quiet, a few missed days, momentum stalling, he gets restless and asks you to take him for a walk. It\'s his way of saying "let\'s not overthink this, just move today." One short walk is often all it takes to restart a streak.' },
      { t: 'quote', text: 'You don\'t have to be motivated. You just have to take the dog out.' },
      { t: 'h', text: 'He grows with you' },
      { t: 'p', text: 'Dub changes with your mood and your progress, happy and panting when you\'re winning, a little concerned when you\'ve drifted. And if dogs aren\'t your thing, reach level 2 and you can switch Dub to a cat. More to unlock as you climb.' },
      { t: 'p', text: 'Weigh in, tick your habits, and let Dub do the rest. He\'s not going anywhere. 🐶' },
    ],
  },
  {
    id: 'build-habits',
    title: 'How to Build Habits That Actually Stick',
    author: 'Ali Shah',
    readMins: 4,
    tag: 'Habits',
    accent: '#2FD27E',
    dek: 'Motivation gets you started. Systems are what keep you going.',
    body: [
      { t: 'p', text: 'Most people quit a new habit not because they are lazy, but because they bet everything on motivation. Motivation is a feeling, and feelings are weather, they change daily. The people who change their lives don\'t feel more motivated than you. They\'ve just built systems that don\'t need motivation to run.' },
      { t: 'h', text: 'Make it small enough to be stupid' },
      { t: 'p', text: 'The single biggest mistake is starting too big. "Read 30 minutes a day" fails; "read one page" survives. When a habit is small enough that you can do it on your worst day, it stops being negotiable. You can always do more, but you commit to the floor, not the ceiling. The win is showing up, not the size of the showing up.' },
      { t: 'h', text: 'Anchor it to something you already do' },
      { t: 'p', text: 'New habits stick best when they ride on the back of old ones. This is called habit stacking: "After I pour my morning coffee, I take my vitamins." The existing habit is the cue. You don\'t need to remember, the routine reminds you.' },
      { t: 'h', text: 'Never miss twice' },
      { t: 'p', text: 'You will miss days. Life happens. The rule that separates people who keep their habits from people who lose them is simple: never miss twice. One missed day is an accident. Two is the start of a new (worse) habit. Missing once is fine, just don\'t let the exception become the rule.' },
      { t: 'quote', text: 'You do not rise to the level of your goals. You fall to the level of your systems.' },
      { t: 'h', text: 'Make the streak visible' },
      { t: 'p', text: 'A chain of green days is one of the most motivating things in the world, not because of the reward, but because you don\'t want to break it. That\'s the entire idea behind tracking. When progress is visible, your brain treats protecting it as the goal. That\'s exactly what Superdub is built to do: turn invisible consistency into something you can see and defend.' },
      { t: 'p', text: 'Start today. Pick one habit. Make it tiny. Anchor it. And whatever happens this week, never miss twice.' },
    ],
  },
  {
    id: 'habit-tracking',
    title: 'Why Habit Tracking Works (And How to Do It Right)',
    author: 'Ali Shah',
    readMins: 3,
    tag: 'Tracking',
    accent: '#2E8BFF',
    dek: 'What gets measured gets managed, and what gets ticked gets repeated.',
    body: [
      { t: 'p', text: 'Tracking a habit feels almost too simple to matter. You did the thing; you mark it done. But that small act does three powerful things at once, and understanding them is the difference between tracking that changes your life and tracking you abandon by Thursday.' },
      { t: 'h', text: '1. It\'s a cue' },
      { t: 'p', text: 'Opening the app and seeing an unticked habit is itself a reminder to act. The tracker doesn\'t just record behaviour, it prompts it.' },
      { t: 'h', text: '2. It\'s a reward' },
      { t: 'p', text: 'Marking something done releases a genuine hit of satisfaction. The checkmark, the streak ticking up, the bar filling, these are small, immediate rewards for a behaviour whose real payoff (fitness, knowledge, health) is months away. Tracking bridges that gap.' },
      { t: 'h', text: '3. It\'s honest feedback' },
      { t: 'p', text: 'You can\'t lie to a calendar. "I\'ve been pretty consistent" turns out to mean three days out of fourteen. The data is humbling, and that honesty is the point, you can only fix what you can see.' },
      { t: 'h', text: 'How to track without burning out' },
      { t: 'li', text: 'Track few things. Three habits done daily beats ten tracked once.' },
      { t: 'li', text: 'Track the input, not the outcome. "Walked today", not "lost weight". You control inputs.' },
      { t: 'li', text: 'Be honest even when it hurts. A real miss logged is worth more than a fake done.' },
      { t: 'li', text: 'Review weekly. Patterns only show up over time, which day do you always slip?' },
      { t: 'p', text: 'Done right, tracking turns your intentions into a feedback loop. You see the truth, you protect your streak, and slowly the habit stops being something you do and becomes something you are.' },
    ],
  },
  {
    id: 'goal-setting',
    title: 'Goal Setting That Actually Gets You There',
    author: 'Ali Shah',
    readMins: 4,
    tag: 'Goals',
    accent: '#A855F7',
    dek: 'A goal without a system is just a wish with a deadline.',
    body: [
      { t: 'p', text: 'Everyone sets goals in January. Almost no one keeps them by March. The problem is rarely the goal itself, it\'s that we set the destination and ignore the vehicle. Here\'s how to set goals that survive contact with real life.' },
      { t: 'h', text: 'Set the goal, then forget it' },
      { t: 'p', text: 'This sounds backwards, but it\'s the key. Use the goal to set the direction, "lose 8kg", "read 12 books", then put your attention entirely on the daily system that gets you there. You don\'t lose 8kg by thinking about 8kg. You lose it by hitting your steps and your calories today. Fall in love with the process; let the outcome take care of itself.' },
      { t: 'h', text: 'Make it specific and measurable' },
      { t: 'p', text: '"Get fit" is not a goal, it\'s a vibe. "Walk 8,000 steps a day, five days a week" is a goal, because you can know, unarguably, whether you did it. Vague goals give your brain room to negotiate. Specific ones don\'t.' },
      { t: 'h', text: 'Work backwards from the deadline' },
      { t: 'p', text: 'Take the outcome and divide it by the time. Want to lose 8kg in four months? That\'s about 0.5kg a week, a calm, sustainable pace. Now you\'re not chasing a scary number; you\'re chasing this week\'s half-kilo. Big goals become a series of small, boring, achievable ones.' },
      { t: 'quote', text: 'Goals are good for setting a direction, but systems are best for making progress.' },
      { t: 'h', text: 'Build in the comeback' },
      { t: 'p', text: 'You will fall behind at some point. Plan for it now, while you\'re calm. Decide in advance: "If I miss a week, I don\'t scrap the goal, I just start again from where I am." The people who reach their goals aren\'t the ones who never fall off. They\'re the ones who get back on fastest.' },
      { t: 'p', text: 'Set the destination. Then pour your energy into the next single step. That\'s the whole game.' },
    ],
  },
  {
    id: 'daily-weigh-in',
    title: 'Why You Should Weigh Yourself Every Day',
    author: 'Ali Shah',
    readMins: 4,
    tag: 'Weight loss',
    accent: '#FFB928',
    dek: 'The scale isn\'t a judge. It\'s a sensor, and daily data beats weekly guesswork.',
    body: [
      { t: 'p', text: 'A lot of advice tells you to weigh yourself once a week, or to throw the scale away entirely. I think that\'s a mistake, and the research agrees. People who weigh themselves daily lose more weight and keep it off better. But only if you understand what the number actually means.' },
      { t: 'h', text: 'Your weight is noisy, that\'s normal' },
      { t: 'p', text: 'Your body weight can swing 1–2kg in a single day from water, salt, carbs, hormones, and what\'s simply still in your digestive system. None of that is fat. If you only weigh weekly, you might catch a random high day and feel like a failure when you\'re actually doing fine. Daily data lets you see through the noise.' },
      { t: 'h', text: 'Watch the trend, not the day' },
      { t: 'p', text: 'No single weigh-in tells you anything. The trend over two weeks tells you everything. This is why Superdub draws a smoothed trend line through your daily dots, one day up, one day down, but the line quietly heading where you want to go. Judge yourself by the line, never the dot.' },
      { t: 'h', text: 'Weigh under the same conditions' },
      { t: 'li', text: 'First thing in the morning.' },
      { t: 'li', text: 'After using the bathroom.' },
      { t: 'li', text: 'Before eating or drinking.' },
      { t: 'li', text: 'Same scale, minimal clothing.' },
      { t: 'p', text: 'Consistency in how you measure removes most of the noise before it ever reaches the chart.' },
      { t: 'h', text: 'It keeps you honest and aware' },
      { t: 'p', text: 'The daily step on the scale is a tiny moment of accountability. It keeps your goal in front of you without obsession. A weekend of overeating shows up gently on Monday, you adjust, and you move on, long before it becomes a month of drift.' },
      { t: 'quote', text: 'You\'re not weighing yourself to feel bad. You\'re collecting data so you can make good decisions.' },
      { t: 'p', text: 'Step on the scale every morning. Log the number. Ignore the daily wobble. Trust the line. That calm, boring habit, repeated, is how the weight actually comes off.' },
    ],
  },
];
