// Superdub release notes — the major updates, newest first. Dated to when they
// actually shipped. Rendered as the "What's New" timeline in the Success Kit.
export interface UpdateEntry {
  date: string;        // ISO yyyy-mm-dd
  emoji: string;
  title: string;
  summary: string;
  points: string[];
}

export const UPDATE_LOG: UpdateEntry[] = [
  {
    date: '2026-07-14',
    emoji: '💬',
    title: 'Dub can actually talk now',
    summary: 'Talk to Dub is a real conversation. His weigh-in read opens a chat where you tap questions and he answers from your own numbers, on the spot. He also writes you a morning brief and an evening debrief, and his room now reacts to how your day is really going.',
    points: [
      'Tap Dub anywhere you could before and the chat opens. Ask if you are on pace, why the scale is up, whether you will hit your goal by its date, how much your body burns, how you slept, or how to level up faster. Every answer comes from your own data, and the maths page shows exactly how.',
      'Questions only appear when Dub has the data to answer them, and some come from patterns he spotted himself, like the day a habit tends to slip.',
      'Before noon his room shows a morning brief: your sleep, the scale move, one job for today, and your step and calorie aims. After 6 PM you get the debrief: how you landed against what your body burns, habits closed, and one thing for tomorrow.',
      'His room is alive now. A clean sweep of your habits earns sparkles, a flat scale makes him look worried, and his current thought floats in a speech bubble. Tap it to chat.',
    ],
  },
  {
    date: '2026-07-11',
    emoji: '🎚️',
    title: 'Choose the daily prompts you want',
    summary: 'You now decide which daily check-ins Superdub asks for. Turn the morning weigh-in off if you are not running a weight plan, and pick whether you are prompted for sleep, energy and mood. Mood and energy also start from a blank slider, so nothing is pre-picked for you.',
    points: [
      'Open the menu and find Daily prompts. Toggle Weigh-in, Sleep, Energy and Mood on or off, each one on its own.',
      'The morning weigh-in now follows your plan by default: on while you have an active weight plan, off if you do not. Turn it back on any time from the menu.',
      'Mood and Energy start with no point set. The slider is blank until you tap and slide to lock in your answer, so you are never nudged toward a default.',
      'A prompt with everything switched off simply stops appearing. Turn a field back on and it returns.',
    ],
  },
  {
    date: '2026-07-11',
    emoji: '📌',
    title: 'Give a weekly, monthly or yearly habit its own day',
    summary: 'A non-daily habit can now run on a set day. Pick a weekday for a weekly habit, a date for a monthly one, or a month and day for a yearly one. It anchors the tick, shows up in Today as it approaches, and only nudges you on its day.',
    points: [
      'Open a weekly, monthly or yearly habit and choose the day it runs on, from a weekday, a day of the month, or a month and date. Leave it on Any day to keep the old anytime-in-the-period behaviour.',
      'The circle by the title and the calendar now aim at that scheduled day, so a tick lands where you meant it.',
      'The Today tab lists a scheduled habit as its day approaches, and flags it once the day has passed and it is still not done.',
      'If you set a reminder on a scheduled habit, the push only comes on its day, not every day of the period.',
    ],
  },
  {
    date: '2026-07-11',
    emoji: '🟡',
    title: 'Mark a habit day Not Applicable, plus a fuller Progress page',
    summary: 'Some days a habit simply does not apply. You can now mark a day Not Applicable so it sits out neutrally, without denting your streak. Past days you never logged now show a yellow question mark, and the Progress page gains a Today list and a clearer Weight Plan tab.',
    points: [
      'Long press a weekday circle to set Not Applicable, a grey dash that never counts as a miss. Tap still marks done, double tap marks missed. The big button and calendar cycle done, missed, N/A, then blank.',
      'A day you never reported now shows a yellow question mark instead of a plain grey ring, so unlogged days read differently from days you actively skipped.',
      'Progress has a new Today tab: your to-dos due this week, plus any weekly or monthly habit whose period closes within three days and is still not done.',
      'The old Today tab is now Weight Plan. It shows your gauge and steps when a goal is set, or a prompt to start a plan when one is not.',
      'The Habits section lists the habits for the cadence you pick, the calendar reopens and closes with a smooth animation, and an over-target calorie ring now holds a steady yellow instead of flashing red.',
    ],
  },
  {
    date: '2026-07-11',
    emoji: '⏰',
    title: 'Set a reminder on any habit',
    summary: 'Open a habit and pick an hour to be nudged. Superdub sends you a push at that time, unless you have already ticked it off for the day.',
    points: [
      'Open any habit and choose a reminder time from Off through the hours of the day. It saves straight away.',
      'You get one push a day per habit at the hour you set, and it stays quiet on days you have already done it.',
      'Reminders ride on notifications, so make sure they are switched on in the cog menu under Notifications.',
    ],
  },
  {
    date: '2026-07-11',
    emoji: '🗓️',
    title: 'Weekly, monthly and yearly habits get their own calendar',
    summary: 'Open the calendar on a weekly, monthly or yearly habit and it now shows one cell per period, weeks, months or the year, instead of a grid of single days that never fit its rhythm.',
    points: [
      'Daily habits keep the familiar month grid of days.',
      'Weekly habits show the weeks of the month; monthly habits show all twelve months; yearly shows the year. Tap a period to mark it, same as before.',
    ],
  },
  {
    date: '2026-07-11',
    emoji: '📅',
    title: 'Habit due dates, and a sleep-chart fix',
    summary: 'You can now pin a due date to any habit, whatever its cadence. And sleep will show on your chart even on nights you logged hours without exact bed and wake times.',
    points: [
      'Open any habit and set a due date. It shows on the card and turns red once it is overdue and still not done. Tap clear to drop it.',
      'The sleep chart now falls back to the hours line when a night was logged without bed and wake times, so those nights no longer vanish from the chart.',
    ],
  },
  {
    date: '2026-07-11',
    emoji: '🃏',
    title: 'Habit cards, cleaned up and easier to read',
    summary: 'The habit card no longer crams everything onto one line. The name sits up top with its circle, level, streak and controls fall into place beneath, and the month calendar now opens right where you track your streak.',
    points: [
      'The name and its done-circle sit on the top row. Below the name: your level, the expand chevron and your streak length. Star and Archive move to their own controls on the right.',
      'Open a card and the streak line now carries a calendar button. Tap it and the month view opens in place of the Mon-to-Sun row, so past days and this week live in the same spot.',
      'The "recent miss" stat lost its medal (a medal for missing never made sense) and now reads clearly, turning amber only when you have actually slipped.',
      'On Progress, tap the Steps box under Yesterday to log yesterday\'s steps right there.',
    ],
  },
  {
    date: '2026-07-11',
    emoji: '🎯',
    title: 'Your Plan is back, right on the Today tab',
    summary: 'Progress → Today now shows your weight plan again: the start-to-goal semi-circle, your Weight This Week chart, and your step count, all in one place. Quit habits also moved to the left of Daily.',
    points: [
      'Open Progress and tap Today. Your weight-journey gauge is back: current weight in the middle, how far along you are from start to goal, with the time you have used underneath.',
      'Right below it sits Weight This Week, your smoothed trend, safe-zone corridor and 28-day direction, plus your step goal and how yesterday went.',
      'On the Habits page, the grey Quit panel now sits to the left of Daily. The page still opens on Daily each time, so Quit is one swipe left when you want it.',
      'Nothing was lost, the full Plan page is still one tap away in the cog menu.',
    ],
  },
  {
    date: '2026-07-11',
    emoji: '⭐',
    title: 'Make it yours: star, reorder, and gender Dub',
    summary: 'Three small touches that make your habits feel like yours. Star the ones that matter, drag them into the order you like, and set whether Dub is a he, she or they.',
    points: [
      'Tap the star on any habit card to mark it a favourite. Your starred habits then show up on Progress, under Today and Yesterday, so the ones that matter are always in view.',
      'Grab the handle on the left of a habit card and drag to reorder your list. The order sticks, exactly how you arranged it.',
      "Dub can now be a he, she or they. Set it in Profile, under Companion, next to where you pick the dog or cat. Dub's coaching updates to match.",
    ],
  },
  {
    date: '2026-07-11',
    emoji: '📓',
    title: 'A Journal on your Lists, with a mood',
    summary: 'Lists gains a fourth tab. Write a line about your day, tag how you felt, and Dub folds that mood into the patterns he reads for you.',
    points: [
      'Open Lists and tap the new Journal tab, next to Goals.',
      'Write whatever is on your mind, then tag your mood from rough to great. The mood is optional, the writing is yours.',
      'Every entry is saved newest first, with its mood and the time you wrote it.',
      'Dub reads those moods alongside your check-ins, so the days you journal feed straight into what he spots about your steps, habits and weight.',
    ],
  },
  {
    date: '2026-07-11',
    emoji: '⏱',
    title: 'Habits to quit: a clock that counts up',
    summary: 'Swipe past your daily habits to the new Quit panel. Set the moment you stopped, and a live timer counts every day, hour and minute you stay clean, filling toward your first 30 days.',
    points: [
      'On the Habits page, swipe your habit cards left past Daily, Weekly, Monthly and Yearly to reach the new grey Quit panel.',
      'Add the thing you are quitting and set when you stopped. A continual timer then counts up in days, hours, minutes and seconds.',
      'A bar fills as you go, reaching full at 30 clean days. There is no daily tick to remember, the clock just runs.',
      'Slipped? Tap Rewind and the clock restarts from now. No shame, no lost history, just a fresh run.',
    ],
  },
  {
    date: '2026-07-11',
    emoji: '🐾',
    title: 'Dub gets his own tab, and a sharper eye',
    summary: 'Dub moves off the sidelines into his own spot on the bottom bar. Tap him any time for a check-in, a read on where you are, and the patterns he has dug out of your own data.',
    points: [
      'Dub now sits in the middle of the bottom bar. Your Profile moves into the cog menu, top right, where all your settings and customization already live.',
      'Open Dub for a live read on your weight trend and habits, plus a "Check in with Dub" button whenever you want his full report.',
      'Dub now reads your history for patterns: which weekday a habit slips most, whether a habit goes with more steps or a better mood, and whether keeping it up tracks with your weight coming down.',
      'It is all worked out on your device from your own numbers. No guessing, no cloud, and it unlocks once you have about ten days of data.',
    ],
  },
  {
    date: '2026-07-09',
    emoji: '🌍',
    title: 'The Global habit: one thing, all of us',
    summary: 'A slowly turning planet now sits by your level ring. Tap it for this month\'s shared habit that the whole community levels up together.',
    points: [
      'Tap the spinning planet, top left of your level ring, to open The Global habit.',
      'This July it is one simple thing: do a good deed today. Log it once a day.',
      'Every deed levels the habit up for you and adds to one shared community total that everyone climbs together.',
      'When we reach 10,000 XP as a community, everyone who has chipped in at least 100 XP unlocks a brand new colour for Dub: pure white. Equip it on your Level page whenever you like.',
    ],
  },
  {
    date: '2026-07-08',
    emoji: '✨',
    title: 'A big polish pass, and your Data Table is back',
    summary: 'A sweep of fixes and a cleaner feel across the app. Your full data table returns to the menu, the home logging strip is redesigned, and late nights get their own look.',
    points: [
      'Your Data Table is back. Open the menu (the cog), tap Data Table, and see or edit every day of weight, steps and habits in one grid.',
      "Today's Log on the home screen is redesigned into clean rows, each lighting up in its own colour as you log it.",
      'The daily check-in is now a calm evening reflection: rate your mood and how eating went once the day is actually over. Mornings just ask about sleep and energy.',
      'After midnight the app stays on the previous day until 2 AM, so a late night logs where you expect. The screen turns to a starlit night with a banner you can dismiss or tap to jump ahead.',
      'Your streak now burns as a live flame that grows hotter the longer you keep it going.',
      'Big number fixes: estimated calories no longer spike into the tens of thousands, your steps calendar fills in correctly (green for goal hit, orange for under), and sleep reads in clean half hours.',
      'Sleep and mood now share one timeline so you can read them together, and going over your target shows in red instead of purple.',
      'Food logging has been retired. Superdub estimates your intake from your weight trend, steps and activity, so there is nothing to type in.',
    ],
  },
  {
    date: '2026-07-07',
    emoji: '📊',
    title: 'Progress charts actually draw again',
    summary: 'The blank Progress charts are fixed for real this time. They now fill their space and render properly on every tab.',
    points: [
      'Fixed the empty chart boxes: the chart area now gets a real measured height instead of collapsing to nothing, so Weight, Steps and the rest draw again and fill the screen.',
    ],
  },
  {
    date: '2026-07-07',
    emoji: '🌙',
    title: 'Sleep is now a slide-between-two-points',
    summary: 'The morning vitals sleep step is a two-handle slider across the night. Drag one point to when you went to bed and the other to when you woke, and both times are saved.',
    points: [
      'Set sleep by dragging two thumbs on a 6pm-to-6pm track: one for bedtime, one for wake time. The band between them is your night, and the hours are worked out for you.',
      'Because it now captures when you actually woke, your sleep candlestick chart fills in properly again, coloured by mood.',
    ],
  },
  {
    date: '2026-07-06',
    emoji: '⏰',
    title: 'Exercise and nutrition prompts, timed to your day',
    summary: 'The check-in is now four focused prompts that each show up at the right time and have their own notification: morning weigh-in, morning vitals, a post-workout loop, and an evening eating check.',
    points: [
      'New exercise prompt: a one-tap "Did you close your loop today?" that appears after your workout hour, and its notification opens straight to it.',
      'New evening nutrition prompt: an "eating today vs target" ring that shows up after your nutrition hour if you have not logged, with a quick jump to log calories.',
      'Each prompt is time-locked and has a matching notification you can time in the menu under Notifications (Morning, Nutrition, Workout).',
      'The old all-in-one check-in no longer pops up on its own; it stays in the menu under Log Check-in for the fuller eating and workout detail.',
    ],
  },
  {
    date: '2026-07-06',
    emoji: '🌗',
    title: 'A sleek new morning check-in: slide, slide, done',
    summary: 'The Check-in on Home is now a focused vitals prompt with sliders. Set last night\'s sleep, then mood, then energy, each sliding into place as you go.',
    points: [
      'Tap Check-in and you get a clean pop-up: a sleep slider from 4 to 12 hours, then mood and energy on 1 to 10 sliders that appear one after another so it never feels busy.',
      'It saves just those vitals without touching anything else you have logged that day.',
      'This is the first of the split, time-based prompts. Focused exercise and evening nutrition pop-ups are next.',
    ],
  },
  {
    date: '2026-07-06',
    emoji: '🗓️',
    title: 'Nicer due dates on Lists, and they finally stick',
    summary: 'The clunky date box on Lists is gone. Add a task, then tap the calendar to pick a due date from a tidy dropdown, and it now saves properly and rides under the task.',
    points: [
      'Add a task, then tap the calendar button to set a due date from a dropdown of quick picks (Today, Tomorrow, Next week) or a date of your choice, instead of the raw date box that sat awkwardly in the row.',
      'Due dates now actually save: before they vanished on refresh, now they stick and show under the task, turning red when overdue.',
      'Log Steps dropped its separate date field, since the calendar already picks the day. The Steps box now shows which day you are logging.',
    ],
  },
  {
    date: '2026-07-06',
    emoji: '📅',
    title: 'A Yesterday tab that grades your day, with Today on the way',
    summary: 'The first Progress tab is now Yesterday: your closing numbers for the day just gone, at a glance. A new Today tab is coming soon and will show live targets.',
    points: [
      'New Yesterday tab: calories eaten versus target, steps taken, sleep and mood, and how many habits you closed, all in one glance at how the day actually went.',
      'A Today tab now sits next to it, holding the spot for live daily targets. It says coming soon for now.',
      'Dub still gives you the plain-English verdict on yesterday at the top of the tab.',
    ],
  },
  {
    date: '2026-07-06',
    emoji: '🩹',
    title: 'Fixed the blank Progress charts, plus a tidier menu',
    summary: 'The Progress charts were rendering as empty boxes after the height-lock change. They fill their space properly again, and the settings menu got a cleanup with more quick-log options.',
    points: [
      'Fixed the Progress charts showing up blank: they now fill the locked height correctly instead of collapsing to nothing.',
      'Quick log in the menu now covers everything you can track by hand: weight, steps, check-in, and food and calories.',
      'Menu cleanup: removed the old Tracker shortcut, moved Personalise into Settings, and tucked The Maths under About Superdub.',
      'Dub is a touch bigger at the top of each Progress tab, because he was feeling left out.',
    ],
  },
  {
    date: '2026-07-06',
    emoji: '🔒',
    title: 'Progress pages are height-locked, with Dub talking up top',
    summary: 'Every Progress tab now fits one screen with no scrolling. Dub gives you a line at the top of each tab (tap him for the full read), and the chart fills all the space below it.',
    points: [
      'No more scrolling on the Progress tabs: each one is locked to a single screen, so the chart stretches as tall as it can instead of leaving gaps.',
      'Dub sits at the top of every tab with a short read on what you are looking at. Tap him and he opens the full coaching breakdown.',
      'Swiping left or right on the chart itself now flips to the next tab, so you can move through Today, Weight, Steps and the rest without reaching for the chips.',
      'Tap a point on a chart to see its details; the tooltip stays put so you can actually read it.',
    ],
  },
  {
    date: '2026-07-06',
    emoji: '📐',
    title: 'Progress tab: taller charts, forward targets, sleep and mood together',
    summary: 'Every Progress chart now fills a taller uniform canvas so tabs no longer jump, the Today gauges point at what to hit next, the verdict reads yesterday back to you, and Sleep and Mood share one panel.',
    points: [
      'All Progress charts share one taller height, so switching between Today, Weight, Steps and the rest no longer shifts the layout, and the graphs use the full screen instead of leaving dead space.',
      'The Today matrix is now forward-looking: Activity shows the steps you still need to hit today\'s target, and Vitals recommends how many hours to aim for tonight to steady tomorrow\'s energy.',
      'Dub\'s verdict up top is a clean retrospective read on yesterday: what you ate versus target, your safe-zone status, and the week\'s change.',
      'Sleep and Mood moved onto a single panel, stacked on a shared date axis so you can see how last night\'s rest and the next day\'s mood track together.',
    ],
  },
  {
    date: '2026-07-06',
    emoji: '🎯',
    title: 'The Today tab is now a Live Target Matrix',
    summary: 'The Progress "Today" view is rebuilt: a plain-text read from Dub up top, then a fixed four-gauge matrix of live pace and buffers, with the chart chips moved underneath and the pager dots gone.',
    points: [
      'New Live Target Matrix: four live gauges in a fixed 2x2 grid. Intake shows your calorie runway as a ring (and flashes a critical buffer if you go over), Activity tracks your steps against where you should be by now, Vitals reads last night\'s sleep and predicts your afternoon energy, and Focus surfaces the one habit still open today (tap it to tick it).',
      'Dub\'s verdict is now plain text at the top of Today, a live read on where you stand right now rather than a boxed number.',
      'The chart chips (Today, Weight, Habits and the rest) moved directly under the visualization, and the little pagination dots are gone. Tap a chip to switch instantly.',
      'The Today matrix is locked to the same width as the trend charts, so moving between them no longer shifts the layout.',
    ],
  },
  {
    date: '2026-07-06',
    emoji: '🔔',
    title: 'Reminders that fit your day, and a Core Habits matrix',
    summary: 'Notifications now cover the whole loop (morning, evening, and an optional post-workout nudge), and The Ascension shows your four daily loops as tokens that light up gold as you close them.',
    points: [
      'Notifications settings now let you pick three separate times: a morning weigh-in, an evening nutrition check, and (optional) a post-workout "did you close your exercise loop?" nudge. Each one stays quiet if you have already logged that thing.',
      'Tapping a reminder drops you straight into the right place: the weigh-in opens the morning check-in, the workout nudge opens your daily ritual, and the nutrition one opens Food Log.',
      'New Core Habits matrix on The Ascension, under your level ring: four tokens (Weight, Sleep and Energy, Steps, Calories) that light gold the moment you close each loop for the day.',
      'The morning check-in now opens with a simple "Did you weigh yourself?" Yes or No, so a quiet no just stops the nagging for the day instead of sitting in your way.',
    ],
  },
  {
    date: '2026-07-06',
    emoji: '😴',
    title: 'Sleep as candlesticks, plus fixes across the app',
    summary: 'Your nights now read as bed-to-wake candles coloured by your morning mood, and a batch of fixes lands across Habits, Progress, Steps and Profile.',
    points: [
      'New sleep chart: each night is a candle whose body runs from when you went to bed to when you woke, so its length is the time you actually slept. The colour is that morning\'s mood (green good, red rough), so you can see how sleep and mood move together.',
      'Habits: double-tap a day circle to mark it as a miss (a single tap still marks it done), and your XP and level ring now update the instant you tick a habit.',
      'Log Steps: a month calendar (green for logged days, red for missed) that stays open, so you can fill several days in one go.',
      'Progress: one swipe now moves exactly one chart, and the Today panel sits full-height without scrolling.',
      'Fixes: the water ring tilts the correct way now, The Maths no longer runs off the side of the screen, and the Plan section on Profile no longer spills over the edge.',
    ],
  },
  {
    date: '2026-07-06',
    emoji: '🎠',
    title: 'Daily Log, swipeable charts & a fuller ring',
    summary: 'A vitals strip that reinforces your daily logging, a swipe-through chart carousel with Dub\'s read on each, and a liquid ring that fills the whole disc.',
    points: [
      'New "Daily Log" strip at the top of Habits: weigh-in, steps and check-in chips that tick green as you log, plus a logging streak to keep the data flowing.',
      'Progress charts are now a swipeable carousel, one full-width chart at a time with Dub\'s interpretation underneath, instead of an endless scroll.',
      'Liquid ring themes now fill the entire disc (no separate ring), the water level alone shows your progress.',
      'Fixed the daily check-in running off the top of the screen, it scrolls neatly within the sheet now.',
    ],
  },
  {
    date: '2026-07-05',
    emoji: '🌙',
    title: 'Your daily ritual, sleep, and a sharper look',
    summary: 'A morning ritual with a sleep slider, a new Progress hero that leads with the number that matters, and a top-to-bottom design pass.',
    points: [
      'New "Yesterday\'s Verdict" hero at the top of Progress: your estimated intake vs target at a glance, with an under/over chip, safe-zone status, and this week\'s weight change.',
      'The daily check-in is now a proper ritual, add a sleep slider and an optional morning weigh-in without leaving the screen.',
      'Sleep is saved and charted: a new graph on Progress with an 8-hour reference line, so you can see rest against everything else.',
      'One consistent colour language app-wide, green for the body, blue for growth, gold reserved for XP, no more mismatched accents.',
      'The Level page was rebuilt into "The Ascension": a gold identity, a level ladder, and a cleaner cosmetics shelf, with emoji removed from the app\'s chrome.',
      'Fixed the weight axis (now on the left), the personalise header, and smoothed the liquid ring fill.',
    ],
  },
  {
    date: '2026-07-03',
    emoji: '📐',
    title: 'Honest maths & the Liquid ring',
    summary: 'A full audit of every calculation in the app, a new page that shows you the formulas, and a liquid ring theme that moves when you do.',
    points: [
      'Dub now quotes your real weekly change, first and last weigh-in of the week, both numbers shown, so you can check him against the chart.',
      'New "The Maths" page in the cog menu: every formula written out with worked examples, straight from the code.',
      'One unified step-burn formula everywhere (three pages used to disagree), sex-aware calorie maths, and the safe-zone corridor no longer skips its first day.',
      'Editing your Weight Plan no longer resets your start date, your corridor progress is safe.',
      'New Liquid ring theme at level 5: a water fill that rises with your XP and sloshes when you tilt your phone.',
      'Macros are gone, Superdub is calories-first now. Simpler logging, same results.',
    ],
  },
  {
    date: '2026-06-29',
    emoji: '🐶',
    title: 'Meet Dub, your coach',
    summary: 'Superdub got a companion, a little robotic Yorkie who reads your data and coaches you in plain English.',
    points: [
      'Dub gives you an honest read after every weigh-in: a win to protect, what\'s slipping, and one tiny next step.',
      'He sits by your level ring and at the top of Progress, rating how you\'re trending over time.',
      'When momentum stalls, Dub asks to be taken for a walk, a nudge to just move today.',
      'Reach level 2 and you can switch Dub from a dog to a cat. More to unlock as you climb.',
    ],
  },
  {
    date: '2026-06-28',
    emoji: '🔐',
    title: 'Sign in with Google',
    summary: 'Create your account or log in with one tap using Google, no password to remember.',
    points: [
      'New Google users still get the full onboarding so your targets stay personalised.',
      'Your identity is always verified securely on our server.',
    ],
  },
  {
    date: '2026-06-28',
    emoji: '📚',
    title: 'The Success Kit',
    summary: 'A new home for guides, recommended books and original Superdub articles to help you build habits and reach your goals.',
    points: [
      'Original reads on habits, habit tracking, goal setting and daily weighing.',
      'Hand-picked book recommendations across focus, discipline, weight and health.',
      'Every page now has one unified menu (the cog), settings, navigation and quick-logging in one place.',
    ],
  },
  {
    date: '2026-06-28',
    emoji: '⭐',
    title: 'Levels, rewards & ring themes',
    summary: 'Your XP now means something. A proper level system with meaningful titles, a reward at every level, and unlockable cosmetics.',
    points: [
      'Fifteen levels from "First Day" to "Transcendent", each granting a named reward.',
      'Unlockable level-ring themes, equip the one you\'ve earned.',
      'A full-screen celebration when you level up.',
      'A Duolingo-style day-streak flame in the header to keep your run alive.',
    ],
  },
  {
    date: '2026-06-28',
    emoji: '✅',
    title: 'Habit cards, reimagined',
    summary: 'The whole habit experience was rebuilt, cleaner, more informative, and more satisfying to tick.',
    points: [
      'Collapsible cards: a clean summary that expands into stats, streaks and history.',
      'A persistent habit level that grows with total days, it never resets on a miss.',
      'Missed due days now auto-mark as failed so your week tells the truth.',
      'A redesigned stat panel with your earned title, level, streak and XP.',
    ],
  },
  {
    date: '2026-06-28',
    emoji: '🗂️',
    title: 'Archived habits & easier weigh-ins',
    summary: 'Archive habits to a dedicated screen, restore them any time, or delete them for good, plus a faster way to log your weight.',
    points: [
      'A proper Archived Habits screen with restore and permanent-delete.',
      'Weigh-ins are now tap-to-type, pre-filled with your last weight.',
    ],
  },
  {
    date: '2026-06-25',
    emoji: '📈',
    title: 'Progress charts overhaul',
    summary: 'Weight and habits split into their own charts, with smoother panning and a clearer view of where you\'re heading.',
    points: [
      'Separate Weight Trend and Habits charts on Progress.',
      'Drag the chart directly to pan through time windows.',
      'A forward projection line shows where your current pace is taking you.',
    ],
  },
];
